### ISSUE TITLE
 missing `report_new_callstack_frame` in implementation

### ISSUE THREAD

**Issue by bap2pecs** [matter-labs/era-zkevm_test_harness#3]
I am following https://github.com/matter-labs/zksync-era/blob/main/docs/development.md for local development. However, when I run `zk init`, I got error

```
error[E0046]: not all trait items implemented, missing: `report_new_callstack_frame`
    --> /Users/<redacted>/.cargo/git/checkouts/era-zkevm_test_harness-22d97ff2abf02d7d/cfac36a/src/witness/oracle.rs:1250:1
     |
1250 | impl<E: Engine> WitnessOracle<E> for VmWitnessOracle<E> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `report_new_callstack_frame` in implementation
     |
     = help: implement the missing item: `fn report_new_callstack_frame(&mut self, _: &ExecutionContextRecord<E>, _: sync_vm::vm::primitives::UInt32<E>, _: &sync_vm::franklin_crypto::plonk::circuit::boolean::Boolean, _: &sync_vm::franklin_crypto::plonk::circuit::boolean::Boolean) { todo!() }`
```

After digging into it, I found it's caused by https://github.com/matter-labs/era-sync_vm/commit/5aedffa442134d6e4d879566aac5434c7ae683cf

it added

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/111917526/229683196-2aa344a3-f717-4180-b6e0-f5810de370d9.png">

but it's not implemented in `WitnessOracle` (https://github.com/matter-labs/era-zkevm_test_harness/blob/main/src/witness/oracle.rs)

**Comment by bap2pecs** [comment]
quick workaround:

edit `/Users/<redacted>/.cargo/git/checkouts/era-zkevm_test_harness-22d97ff2abf02d7d/cfac36a/src/witness/oracle.rs` manually:

by adding
```
fn report_new_callstack_frame(
        &mut self,
        new_callstack: &ExecutionContextRecord<E>,
        new_depth: UInt32<E>,
        is_call: &Boolean,
        execute: &Boolean,
    ) {
      // TODO: need implementation
    }
```

<img width="666" alt="image" src="https://user-images.githubusercontent.com/111917526/229684027-20e826c0-73d5-4d27-bcbe-94fa28e098dc.png">
